/**
  Copyright (c) 2011 Freescale Semiconductor
* Autogenerated PVG File SPH by PVG to C converter Ver 1.0.0.7
* This is the source file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#include "SPH.h"



const float SPH_PVGRampData[] =
{
0
};



const PVG_Ramps_t SPH_PVGRamps[] =
{
0
};



const PVG_Paints_t SPH_PVGPaints[] =
{
    {0,6912,{0,0,1,1,0},-1160773632,1131530752},
};



const unsigned char SPH_PVGCmdPathData[] =
{
    2,4,
};



const float SPH_PVGPathData[] =
{
    208,-98,208,-88,
};


const PVG_Paths_t SPH_PVGPaths[] =
{
    {1,0,0,0,0,666,6401,6144,5889,4,10,2,16,&SPH_PVGCmdPathData[0],&SPH_PVGPathData[0]},
};



const PVG_Object_t SPH_PVG = 
{
    1,1,0,52617904,-2,206,-86,210,-100,
    SPH_PVGRamps,
    SPH_PVGPaints,
    SPH_PVGPaths,
    0,
    0
};



