/**
  Copyright (c) 2011 Freescale Semiconductor
* Autogenerated PVG File CPshort by PVG to C converter Ver 1.0.0.7
* This is the source file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#include "CPshort.h"



const float CPshort_PVGRampData[] =
{
0
};



const PVG_Ramps_t CPshort_PVGRamps[] =
{
0
};



const PVG_Paints_t CPshort_PVGPaints[] =
{
    {0,6912,{1,1,1,1,0},-1160773632,0},
    {0,6912,{0.7803922,0.7803922,0.7803922,1,0},-1160773632,0},
    {0,6912,{0.6392157,0.05490196,0.05490196,1,0},-1160773632,0},
    {0,6912,{0.6392157,0.05490196,0.05490196,1,0},-1160773632,-1028390784},
    {0,6912,{0.6196079,0.6196079,0.6196079,1,0},-1160773632,0},
};



const unsigned char CPshort_PVGCmdPathData[] =
{
    2,12,12,12,4,0,
    2,12,12,12,4,0,
    2,4,4,4,0,
    2,4,4,4,0,
    2,4,4,4,0,
    2,4,
};



const float CPshort_PVGPathData[] =
{
    1.081543,-90.02246,1.081543,-90.02246,1.081543,-90.02246,2.081543,-90.02246,4.081543,-90.02246,5.081543,-88.03516,5.081543,-86.04688,5.081543,-84.05859,7.09082,-32.22852,7.09082,-32.22852,3.378418,-32.25,
    -1,-90.00098,-1,-90.00098,-1,-90.00098,-2,-90.00098,-4,-90.00098,-5,-88.01367,-5,-86.02539,-5,-84.03711,-7.089844,-32.25,-7.089844,-32.25,-3.255859,-32.22852,
    -2.3125,-32.22949,-3.3125,-32.22949,-2,-90.00098,-1,-90.00098,
    2.378418,-32.25,3.378418,-32.25,2,-90.00098,1,-90.00098,
    -1.273438,-78.63965,1.273438,-78.63965,1,-90.00098,-1,-90.00098,
    0,-78.63965,0,-90.00098,
};


const PVG_Paths_t CPshort_PVGPaths[] =
{
    {2,0,0,0,1,666,6400,6144,5888,1,10,6,88,&CPshort_PVGCmdPathData[0],&CPshort_PVGPathData[0]},
    {2,0,0,0,4,666,6400,6144,5888,1,10,6,88,&CPshort_PVGCmdPathData[6],&CPshort_PVGPathData[22]},
    {2,0,0,0,3,666,6400,6144,5888,1,10,5,32,&CPshort_PVGCmdPathData[12],&CPshort_PVGPathData[44]},
    {2,0,0,0,2,666,6400,6144,5888,1,10,5,32,&CPshort_PVGCmdPathData[17],&CPshort_PVGPathData[52]},
    {2,0,0,0,1,666,6400,6144,5888,1,10,5,32,&CPshort_PVGCmdPathData[22],&CPshort_PVGPathData[60]},
    {1,0,0,0,0,666,6401,6144,5888,1,10,2,16,&CPshort_PVGCmdPathData[27],&CPshort_PVGPathData[68]},
};



const PVG_Object_t CPshort_PVG = 
{
    6,5,0,52749040,-2,-7.089844,-32.22852,7.09082,-90.02246,
    CPshort_PVGRamps,
    CPshort_PVGPaints,
    CPshort_PVGPaths,
    0,
    0
};



