/**
  Copyright (c) 2010 Freescale Semiconductor
* Autogenerated PVG File mustang2 by PVG to C converter Ver. 0.9
* This is the source file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#include "mustang2.h"



const PVG_Ramps_t       mustang2_PVGRamps[];
const PVG_Paints_t      mustang2_PVGPaints[];
const PVG_Paths_t       mustang2_PVGPaths[];
const PVG_Dashes_t    mustang2_PVGDashes[];
const PVG_Patterns_t    mustang2_PVGPatterns[];



const PVG_Object_t mustang2_PVG = 
{
    4,5,4,24,1305540,258.1431,460.4287,430,228,
    &mustang2_PVGRamps,
    &mustang2_PVGPaints,
    &mustang2_PVGPaths,
    NULL,
    NULL
};



const float mustang2_PVGRampData[] =
{
    0,0.8980392,0.8823529,0.8745098,1,
    0,1,1,1,1,
    0.522472,0.6745098,0.682353,0.6901961,1,
    1,0.2745098,0.3137255,0.3294118,1,
    0.005618,0.4901961,0.654902,0.8470588,1,
    0.073034,0.2078431,0.3176471,0.4862745,1,
    0.5,0.8705882,0.9019608,0.9607843,1,
    0.617977,0.7294118,0.8039216,0.9176471,1,
    0.8089889,0.4784314,0.6509804,0.8470588,1,
    1,0.09019608,0.3019608,0.4196078,1,
    0.179775,0.9568627,0.9098039,0.8509804,1,
    0.589888,0.9294118,0.8156863,0.5372549,1,
    1,0.7490196,0.5137255,0.1607843,1,
    0.005618,0.3254902,0.4313726,0.372549,1,
    0.08427,0.1764706,0.4941176,0.4196078,1,
    0.382022,0.572549,0.5215687,0.3372549,1,
    0.561798,0.6352941,0.7058824,0.4823529,1,
    0.662921,0.8431373,0.6941177,0.5411765,1,
    0.955056,0.282353,0.4666667,0.454902,1,
};



const PVG_Ramps_t mustang2_PVGRamps[] =
{
    {4,&mustang2_PVGRampData[0]},
    {6,&mustang2_PVGRampData[20]},
    {3,&mustang2_PVGRampData[50]},
    {6,&mustang2_PVGRampData[65]},
};



const PVG_Paints_t mustang2_PVGPaints[] =
{
    {0,6912,{0,0,0,1,0},-1160773632,0},
    {0,6914,{355.7856,426.5,355.7856,426.5,34.44323},0,0},
    {0,6913,{368.9287,330.7856,429.5,330.7856,1},1,0},
    {0,6914,{356.3569,274.2148,356.3569,274.2148,48.05462},2,0},
    {0,6913,{258.6431,351.0713,319.7856,351.0713,1},3,0},
};


const unsigned char mustang2_PVGCmdPathData[];
const float mustang2_PVGPathData[];

const PVG_Paths_t mustang2_PVGPaths[] =
{
    {3,0,0,0,4,666,6401,6144,5888,1,4,5,32,&mustang2_PVGCmdPathData[0],&mustang2_PVGPathData[0]},
    {3,0,0,0,3,666,6401,6144,5888,1,4,5,32,&mustang2_PVGCmdPathData[5],&mustang2_PVGPathData[8]},
    {3,0,0,0,2,666,6401,6144,5888,1,4,5,32,&mustang2_PVGCmdPathData[10],&mustang2_PVGPathData[16]},
    {3,0,0,0,1,666,6401,6144,5888,1,4,5,32,&mustang2_PVGCmdPathData[15],&mustang2_PVGPathData[24]},
};



const unsigned char mustang2_PVGCmdPathData[] =
{
    2,4,4,4,0,
    2,4,4,4,0,
    2,4,4,4,0,
    2,4,4,4,0,
};



const float mustang2_PVGPathData[] =
{
    319.7856,309.0713,258.6431,309.0713,258.6431,393.0713,319.7856,393.0713,
    406.6426,228.5,306.0713,228.5,306.0713,319.9287,406.6426,319.9287,
    429.5,288.5,368.9287,288.5,368.9287,373.0713,429.5,373.0713,
    391.2144,393.0713,320.3569,393.0713,320.3569,459.9287,391.2144,459.9287,
};
