/**
  Copyright (c) 2010 Freescale Semiconductor
* Autogenerated PVG File POINTER by PVG to C converter Ver. 0.8
* This is the source file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#include "POINTER.h"



const PVG_Ramps_t       POINTER_PVGRamps[];
const PVG_Paints_t      POINTER_PVGPaints[];
const PVG_Paths_t       POINTER_PVGPaths[];
const PVG_Dashes_t      POINTER_PVGDashes[];
const PVG_Patterns_t    POINTER_PVGPatterns[];



const PVG_Object_t	POINTER_PVG = 
{
    2,4,1,24,1305540,391.7476,337.0908,409.252,261.9092,
    POINTER_PVGRamps,
    POINTER_PVGPaints,
    POINTER_PVGPaths,
    NULL,
    NULL
};



const float POINTER_PVGRampData[] =
{
    0,0,0,0,0.8,
    0.1563,0.1333333,0,0,0.8,
    0.5031,0.4745098,0,0,0.8,
    1,1,0,0,0.8,
};



const PVG_Ramps_t POINTER_PVGRamps[] =
{
    {4,&POINTER_PVGRampData[0]},
};



const PVG_Paints_t POINTER_PVGPaints[] =
{
    {0,6912,{1,0,0,0.8,0},-1160773632,1768710958},
    {0,6913,{400.5,264.0342,400.5001,314.1757,0.8},0,1181573490},
    {0,6912,{1,0,0,0.73,0},-1160773632,1124103013},
    {0,6912,{0.8705882,0.1803922,0.1098039,0.73,0},-1160773632,1313429340},
};


const unsigned char POINTER_PVGCmdPathData[];
const float POINTER_PVGPathData[];


const PVG_Paths_t POINTER_PVGPaths[] =
{
    {3,0,187,2,3,666,6401,6144,5888,0.25,4,5,32,&POINTER_PVGCmdPathData[0],&POINTER_PVGPathData[0]},
    {3,0,205,0,1,666,6401,6144,5888,0.5,4,6,40,&POINTER_PVGCmdPathData[5],&POINTER_PVGPathData[8]},
};

const unsigned char POINTER_PVGCmdPathData[] =
{
    2,4,4,4,0,
    2,4,4,4,4,0,
};



const float POINTER_PVGPathData[] =
{
    393.5,265.0342,407.5,265.0342,407.5,262.0342,393.5,262.0342,
    394.936,264.0342,406.0645,264.0342,409,300.5342,400.5,337.0342,392,300.5342,
};