/**
  Copyright (c) 2011 Freescale Semiconductor
* Autogenerated PVG File Audi_n1 by PVG to C converter Ver 1.0.0.7
* This is the header file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _PointerL_H_
#define _PointerL_H_


#include "PVGLoader.h"

extern const PVG_Object_t  PointerL_PVG;

#endif
