/**
  Copyright (c) 2011 Freescale Semiconductor
* Autogenerated PVG File PointerL by PVG to C converter Ver 1.0.0.7
* This is the source file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#include "PointerL.h"



const float PointerL_PVGRampData[] =
{
0
};



const PVG_Ramps_t PointerL_PVGRamps[] =
{
0
};



const PVG_Paints_t PointerL_PVGPaints[] =
{
    {0,6912,{1,0,0,1,0},-1160773632,1108869120},
    {0,6912,{1,1,1,1,0},-1160773632,1148825216},
    {0,6912,{0.7803922,0.7803922,0.7803922,1,0},-1160773632,-1029767680},
    {0,6912,{0.6392157,0.05490196,0.05490196,1,0},-1160773632,1117722496},
    {0,6912,{0.6392157,0.05490196,0.05490196,1,0},-1160773632,0},
    {0,6912,{0.6196079,0.6196079,0.6196079,1,0},-1160773632,-1004053136},
    {0,6912,{0.7803922,0.7803922,0.7803922,1,0},-1160773632,1148829696},
};



const unsigned char PointerL_PVGCmdPathData[] =
{
    2,12,12,12,12,4,4,4,4,0,
    2,12,12,12,12,4,4,4,4,0,
    2,4,4,4,0,
    2,4,4,4,0,
    2,4,4,4,0,
    2,4,
    2,4,
    2,4,4,4,4,0,
};



const float PointerL_PVGPathData[] =
{
    1,-90.00098,1,-90.00098,1,-90.00098,2,-90.00098,4,-90.00098,5,-88.01367,5,-86.02539,5,-84.03711,10,38.79199,10,47.73828,10,56.68359,11.54199,68.25,11.54199,68.25,14,70.59961,9,80.54004,6,79.5459,4.975586,79.5459,
    -1,-90.00098,-1,-90.00098,-1,-90.00098,-2,-90.00098,-4,-90.00098,-5,-88.01367,-5,-86.02539,-5,-84.03711,-10,38.79199,-10,47.73828,-10,56.68359,-11.33398,68.125,-11.33398,68.125,-14,70.59961,-9,80.54004,-6,79.5459,-4.976563,79.5459,
    -5,80.54004,-6,80.54004,-2,-90.00098,-1,-90.00098,
    5,80.54004,6,80.54004,2,-90.00098,1,-90.00098,
    -1.273438,-78.63965,1.273438,-78.63965,1,-90.00098,-1,-90.00098,
    0,-78.63965,0,-90.00098,
    -17,100.333,18,100.333,
    -5.100098,82.96875,0,82.04004,5.125,82.96875,4.663574,66.1875,-4.663086,66.1875,
};


const PVG_Paths_t PointerL_PVGPaths[] =
{
    {2,0,0,0,6,666,6400,6144,5888,1,10,10,136,&PointerL_PVGCmdPathData[0],&PointerL_PVGPathData[0]},
    {2,0,0,0,5,666,6400,6144,5888,1,10,10,136,&PointerL_PVGCmdPathData[10],&PointerL_PVGPathData[34]},
    {2,0,0,0,4,666,6400,6144,5888,1,10,5,32,&PointerL_PVGCmdPathData[20],&PointerL_PVGPathData[68]},
    {2,0,0,0,3,666,6400,6144,5888,1,10,5,32,&PointerL_PVGCmdPathData[25],&PointerL_PVGPathData[76]},
    {2,0,0,0,2,666,6400,6144,5888,1,10,5,32,&PointerL_PVGCmdPathData[30],&PointerL_PVGPathData[84]},
    {1,0,0,1,0,666,6401,6144,5888,1,10,2,16,&PointerL_PVGCmdPathData[35],&PointerL_PVGPathData[92]},
    {0,0,0,0,0,666,6401,6144,5888,1,10,2,16,&PointerL_PVGCmdPathData[37],&PointerL_PVGPathData[96]},
    {2,0,0,0,0,666,6401,6144,5888,1,10,6,40,&PointerL_PVGCmdPathData[39],&PointerL_PVGPathData[100]},
};



const PVG_Object_t PointerL_PVG = 
{
    8,7,0,52486832,-2,-17,100.333,18,-90.00098,
    PointerL_PVGRamps,
    PointerL_PVGPaints,
    PointerL_PVGPaths,
    0,
    0
};



