/**
  Copyright (c) 2009 Freescale Semiconductor
* Autogenerated Image File v2_images
* This is the source file for the Image Array
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _meeterResources_H_
#define _meeterResources_H_

#define uint8_t unsigned char
#define uint32_t unsigned int

extern const uint8_t            v2_s_pointer_Bitmap0[];
extern const uint8_t            v2_s_pointer_Bitmap1[];
extern const uint8_t            v2_s_pointer_Bitmap2[];
extern const uint8_t            v2_s_pointer_Bitmap3[];
extern const uint8_t            v2_s_pointer_Bitmap4[];
extern const uint8_t            v2_s_pointer_Bitmap5[];
extern const uint8_t            v2_s_pointer_Bitmap6[];
extern const uint8_t            v2_s_pointer_Bitmap7[];
extern const uint8_t            v2_s_pointer_Bitmap8[];
extern const uint8_t            v2_s_pointer_Bitmap9[];
extern const uint8_t            v2_s_pointer_Bitmap10[];
extern const uint8_t            v2_s_pointer_Bitmap11[];
extern const uint8_t            v2_s_pointer_Bitmap12[];

extern const uint8_t            v2_b_pointer_Bitmap0[];
extern const uint8_t            v2_b_pointer_Bitmap1[];
extern const uint8_t            v2_b_pointer_Bitmap2[];
extern const uint8_t            v2_b_pointer_Bitmap3[];
extern const uint8_t            v2_b_pointer_Bitmap4[];
extern const uint8_t            v2_b_pointer_Bitmap5[];
extern const uint8_t            v2_b_pointer_Bitmap6[];
extern const uint8_t            v2_b_pointer_Bitmap7[];
extern const uint8_t            v2_b_pointer_Bitmap8[];
extern const uint8_t            v2_b_pointer_Bitmap9[];
extern const uint8_t            v2_b_pointer_Bitmap10[];
extern const uint8_t            v2_b_pointer_Bitmap11[];
extern const uint8_t            v2_b_pointer_Bitmap12[];

extern const uint8_t            v2_images_Bitmap0[];
extern const uint8_t	  	      v2_images_Bitmap1[];
extern const uint8_t			Speed_sign_Bitmap0[];
extern const char 				shadows_Bitmap0[];
extern const char 				shadows_Bitmap1[];

#endif

