/**
  Copyright (c) 2010 Freescale Semiconductor
* Autogenerated PVG File mustang2 by PVG to C converter Ver. 0.9
* This is the header file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _mustang2_H_
#define _mustang2_H_


#include "PVGLoader.h"

extern const PVG_Object_t  mustang2_PVG;

#endif
