/**
  Copyright (c) 2010 Freescale Semiconductor
* Autogenerated PVG File Speed by PVG to C converter Ver. 0.9
* This is the header file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _Speed_H_
#define _Speed_H_


#include "PVGLoader.h"

extern const PVG_Object_t  Speed_PVG;

#endif
