/**
  Copyright (c) 2010 Freescale Semiconductor
* Autogenerated Vector Font File TEST by PVG to C converter Ver not deployed
* This is the header file for the Freescale SVG to Vector Font converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _TEST_H_
#define _TEST_H_


#include "VGFont.h"

extern const VGF_Font_t  TEST_VGF;

#endif
