/**
  Copyright (c) 2009 Freescale Semiconductor
* Autogenerated Image File v2_images
* This is the source file for the Image Array
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _FB_utils_H
#define _FB_utils_H

/*-------------------------------------------------*/
/* sets the position from top left. Only fb0 or fb2 supported */
/*-------------------------------------------------*/

	SetPos(short x, short y, unsigned char fb);


/*-------------------------------------------------*/
/* Enables per pixel alpha on the FG plane */
/*-------------------------------------------------*/

	SetppAlpha();
/*-------------------------------------------------*/
/* Enables global alpha and sets the plane alpha */
/*-------------------------------------------------*/

	SetgAlpha(unsigned char alpha);	

/*-------------------------------------------------*/
/* Fills the fbdev with clearColor */
/*-------------------------------------------------*/

	FB_CLS(int fbdev, int clearColor);
		
#endif

