/**
  Copyright (c) 2010 Freescale Semiconductor
* Autogenerated PVG File POINTER by PVG to C converter Ver. 0.8
* This is the header file for the Freescale PVG to C converter
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _POINTER_H_
#define _POINTER_H_


#include "PVGLoader.h"

extern const PVG_Object_t POINTER_PVG;

#endif
