/**
  Copyright (c) 2009 Freescale Semiconductor
* Autogenerated Image File v2_b_pointer
* This is the source file for the Image Array
* 
* No part of this document must be reproduced in any form - including copied,
* transcribed, printed or by any electronic means - without specific written
* permission from Freescale Semiconductor.
*/

#ifndef _v2_b_pointer_H_
#define _v2_b_pointer_H_


#include "Graphics.h"


#define v2_b_pointer_CLUTOFFSET         (0u)
#define v2_b_pointer_BITSPERPIXEL       (GRAPHICS_32BPP)
#define v2_b_pointer_INITIALPHA         (0xFFu)
#define v2_b_pointer_INITIALCRMAX       (0u)
#define v2_b_pointer_INITIALCRMIN       (0u)
#define v2_b_pointer_ARRAYSIZE          (13)


extern Graphics_Object_t* const v2_b_pointer_GObjectArray[];

#endif
